"""initial

Revision ID: 98244738ac12
Revises: 
Create Date: 2026-06-30 11:14:01.995153

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '98244738ac12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='experimentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=10000), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('contains_injected_fact', sa.Boolean(), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_conversation_messages_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages'))
    )
    op.create_index(op.f('ix_conversation_messages_experiment_id'), 'conversation_messages', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_turn_number'), 'conversation_messages', ['turn_number'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('expected_answer', sa.String(length=200), nullable=False),
    sa.Column('recall_question', sa.String(length=300), nullable=False),
    sa.Column('insertion_turn', sa.Integer(), nullable=False),
    sa.Column('fact_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('alternative_answers', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_facts_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facts'))
    )
    op.create_index(op.f('ix_facts_experiment_id'), 'facts', ['experiment_id'], unique=False)
    op.create_table('metrics_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('memory_recall_accuracy', sa.Float(), nullable=False),
    sa.Column('long_term_recall_rate', sa.Float(), nullable=False),
    sa.Column('information_retention_rate', sa.Float(), nullable=False),
    sa.Column('forgetting_rate', sa.Float(), nullable=False),
    sa.Column('information_survival_score', sa.Float(), nullable=False),
    sa.Column('retrieval_precision', sa.Float(), nullable=False),
    sa.Column('retrieval_recall', sa.Float(), nullable=False),
    sa.Column('context_preservation_score', sa.Float(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('token_efficiency', sa.Float(), nullable=False),
    sa.Column('per_fact_scores', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_metrics_snapshots_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics_snapshots'))
    )
    op.create_index(op.f('ix_metrics_snapshots_experiment_id'), 'metrics_snapshots', ['experiment_id'], unique=False)
    op.create_table('recall_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('test_turn', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('expected_answer', sa.String(length=200), nullable=False),
    sa.Column('model_answer', sa.String(length=2000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('scoring_method', sa.String(length=50), nullable=False),
    sa.Column('retrieved_context', sa.String(length=5000), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('response_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_recall_results_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], name=op.f('fk_recall_results_fact_id_facts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recall_results'))
    )
    op.create_index(op.f('ix_recall_results_experiment_id'), 'recall_results', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_recall_results_fact_id'), 'recall_results', ['fact_id'], unique=False)
    op.create_index(op.f('ix_recall_results_test_turn'), 'recall_results', ['test_turn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recall_results_test_turn'), table_name='recall_results')
    op.drop_index(op.f('ix_recall_results_fact_id'), table_name='recall_results')
    op.drop_index(op.f('ix_recall_results_experiment_id'), table_name='recall_results')
    op.drop_table('recall_results')
    op.drop_index(op.f('ix_metrics_snapshots_experiment_id'), table_name='metrics_snapshots')
    op.drop_table('metrics_snapshots')
    op.drop_index(op.f('ix_facts_experiment_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_conversation_messages_turn_number'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_experiment_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_table('experiments')
    # ### end Alembic commands ###
